### ISSUE TITLE
add more page user interface widgets

### ISSUE THREAD

**Issue by SvenDowideit** [WardCunningham/Smallest-Federated-Wiki#214]
#208 contained a number of things, including my first attempt at this - I'm going to close it, as the UI changes I made didn't work out as well as i'd hoped.

I experience usage impedances when I open more pages than can be seen on my, or my reader's screen.

* there is often no visual indication that there are more pages on the left or right - this can be solved either by having a small portion of the offscreen page peeking, a bottom scrollbar, indicating how many pages are open, or icons, or...
* when opening a story (a collection of pages) to read/edit/refactor or to send to someone else, I start to want to close some, and re-arrange others into an order that better tells the story. This could be solved with a combination of close and drag&drop pages

**Comment by WardCunningham** [comment]
These recently closed suggestions #214, #215 and #216 came at the end of wiki's first year when I was showing wiki around my sponsor's headquarters. The problems they site and in some cases solve have remained as other features grow up around them. Looks mattered, especially clean and consistent looks. That made me overly cautious which I regret.
