### ISSUE TITLE
Hidden node problem

### ISSUE THREAD

**Issue by almereyda** [WardCunningham/Smallest-Federated-Wiki#410]
*Scenario*

1. I'm running a federated wiki on a local network with a private domain. `jon.wiki.lab`.
2. This wiki cannot be forked by internet wikis, as they don't see it, neither on DNS nor via IP.
3. Thus I have a [hidden node problem](https://en.wikipedia.org/wiki/Hidden_node_problem).

*Possible solution*

Mesh networking protocols (like OLSR or Batman) are using relay nodes to distribute data, that cannot reach it's target without additional routing. I'm imagining the client, being a wiki engine itself, to play the relay node and proxy the transmission of the content, i.e. by just creating a new page and uploading the journal from the local storage instead.

The error handling and notificationof the server should then be a little more resilient, though.

**Comment by WardCunningham** [comment]
@almereyda Thanks for the reminder. This issue has been long solved.
